// semantic versioned; see https://semver.org/

#ifndef INCLUDED_GYSANG_VERSION
#define INCLUDED_GYSANG_VERSION

#define GYSANG_VERSION_MAJOR 0
#define GYSANG_VERSION_MINOR 1
#define GYSANG_VERSION_PATCHLEVEL 0
#define GYSANG_VERSION_PRERELEASE_ID
#define GYSANG_VERSION_BUILD_METADATA

#define GYSANG_VERSION_NUMBER (GYSANG_VERSION_MAJOR * 10000 + GYSANG_VERSION_MINOR * 100 + GYSANG_VERSION_PATCHLEVEL)

#define GYSANG_STRINGIFY_VALUE(value_) GYSANG_STRINGIFY(value_)
#define GYSANG_STRINGIFY(value_) #value_

#define GYSANG_VERSION_VERSION_C                                                                           \
    GYSANG_STRINGIFY_VALUE(GYSANG_VERSION_MAJOR)                                                           \
    "." GYSANG_STRINGIFY_VALUE(GYSANG_VERSION_MINOR) "." GYSANG_STRINGIFY_VALUE(GYSANG_VERSION_PATCHLEVEL) \
        GYSANG_VERSION_PRERELEASE_ID GYSANG_VERSION_BUILD_METADATA

#endif
